/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upco.siscom.view;

import java.sql.*;
import com.upco.siscom.dal.ConnectionModule;

/**
 *
 * @author higor
 */
public class NewOrderScreen extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form NewOrderScreen
     */
    public NewOrderScreen() {
        conn = ConnectionModule.connector();
        System.out.println(conn);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOrders = new javax.swing.JMenu();
        miNewOrder = new javax.swing.JMenuItem();
        miEditOrder = new javax.swing.JMenuItem();
        miDeleteOrder = new javax.swing.JMenuItem();
        miSeekOrder = new javax.swing.JMenuItem();
        mnProducts = new javax.swing.JMenu();
        miNewProduct = new javax.swing.JMenuItem();
        miEditProduct = new javax.swing.JMenuItem();
        miDeleteProduct = new javax.swing.JMenuItem();
        miSeekProduct = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 229, 139));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        pnRoot.setBackground(new java.awt.Color(254, 139, 0));
        pnRoot.setName("pnRoot"); // NOI18N

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/upco/siscom/icons/google-logo.png"))); // NOI18N

        javax.swing.GroupLayout pnRootLayout = new javax.swing.GroupLayout(pnRoot);
        pnRoot.setLayout(pnRootLayout);
        pnRootLayout.setHorizontalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        pnRootLayout.setVerticalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(254, 139, 0));

        mnOrders.setText("Comandas");
        mnOrders.setName("mnOrders"); // NOI18N

        miNewOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        miNewOrder.setText("Nova");
        miNewOrder.setName("miNewOrder"); // NOI18N
        mnOrders.add(miNewOrder);

        miEditOrder.setText("Editar");
        mnOrders.add(miEditOrder);

        miDeleteOrder.setText("Excluir");
        miDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteOrderActionPerformed(evt);
            }
        });
        mnOrders.add(miDeleteOrder);

        miSeekOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        miSeekOrder.setText("Consultar");
        mnOrders.add(miSeekOrder);

        jMenuBar1.add(mnOrders);

        mnProducts.setText("Produtos");
        mnProducts.setName("mnOrders"); // NOI18N

        miNewProduct.setText("Novo");
        miNewProduct.setName("miNewOrder"); // NOI18N
        miNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewProductActionPerformed(evt);
            }
        });
        mnProducts.add(miNewProduct);

        miEditProduct.setText("Editar");
        miEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditProductActionPerformed(evt);
            }
        });
        mnProducts.add(miEditProduct);

        miDeleteProduct.setText("Excluir");
        miDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteProductActionPerformed(evt);
            }
        });
        mnProducts.add(miDeleteProduct);

        miSeekProduct.setText("Consultar");
        mnProducts.add(miSeekProduct);

        jMenuBar1.add(mnProducts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miDeleteOrderActionPerformed

    private void miDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miDeleteProductActionPerformed

    private void miNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miNewProductActionPerformed

    private void miEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miEditProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrderScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenuItem miDeleteOrder;
    private javax.swing.JMenuItem miDeleteProduct;
    private javax.swing.JMenuItem miEditOrder;
    private javax.swing.JMenuItem miEditProduct;
    private javax.swing.JMenuItem miNewOrder;
    private javax.swing.JMenuItem miNewProduct;
    private javax.swing.JMenuItem miSeekOrder;
    private javax.swing.JMenuItem miSeekProduct;
    private javax.swing.JMenu mnOrders;
    private javax.swing.JMenu mnProducts;
    private javax.swing.JPanel pnRoot;
    // End of variables declaration//GEN-END:variables
}
