/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upco.siscom.view;

import com.upco.siscom.Config;

/**
 *
 * @author felps
 */
public class TelaSobre extends javax.swing.JFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        lbVersion = new javax.swing.JLabel();
        lbCopyright = new javax.swing.JLabel();
        lbLicensedTo = new javax.swing.JLabel();
        lbCustomer = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        btOk = new javax.swing.JButton();
        lbVersionNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");
        setAlwaysOnTop(true);
        setName("fmSobre"); // NOI18N
        setResizable(false);

        pnRoot.setBackground(new java.awt.Color(255, 255, 255));

        lbVersion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersion.setText("Versão");

        lbCopyright.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCopyright.setText(Config.COPYRIGHT);

        lbLicensedTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLicensedTo.setText("Sob licença para:");

        lbCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCustomer.setText(Config.CUSTOMER_NAME);

        lbName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbName.setText(Config.APP_NAME);

        btOk.setText("OK");
        btOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btOkMouseClicked(evt);
            }
        });

        lbVersionNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersionNum.setText(Config.APP_VERSION);

        javax.swing.GroupLayout pnRootLayout = new javax.swing.GroupLayout(pnRoot);
        pnRoot.setLayout(pnRootLayout);
        pnRootLayout.setHorizontalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addGroup(pnRootLayout.createSequentialGroup()
                        .addComponent(lbVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbVersionNum))
                    .addComponent(lbLicensedTo)
                    .addComponent(lbCustomer)
                    .addComponent(lbCopyright))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRootLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnRootLayout.setVerticalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVersion)
                    .addComponent(lbVersionNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCopyright)
                .addGap(34, 34, 34)
                .addComponent(lbLicensedTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCustomer)
                .addGap(30, 30, 30)
                .addComponent(btOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(371, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOkMouseClicked
        dispose();
    }//GEN-LAST:event_btOkMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbCopyright;
    private javax.swing.JLabel lbCustomer;
    private javax.swing.JLabel lbLicensedTo;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbVersion;
    private javax.swing.JLabel lbVersionNum;
    private javax.swing.JPanel pnRoot;
    // End of variables declaration//GEN-END:variables
}
