/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upco.siscom.view;

import com.upco.siscom.model.bean.Produto;
import com.upco.siscom.model.dao.ProdutoDAO;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felps
 */
public class TelaNovoProduto extends javax.swing.JFrame {

    private static final String TAG = TelaNovoProduto.class.getName();
    
    private Searchable searchable;
    
    /**
     * Creates new form TelaNovoProduto
     */
    public TelaNovoProduto(Searchable searchable) {
        this.searchable = searchable;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        lbCod = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        tfCod = new javax.swing.JTextField();
        lbPorcao = new javax.swing.JLabel();
        tfPorcao = new javax.swing.JTextField();
        lbPreco = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setAlwaysOnTop(true);
        setName("fmNovoProduto"); // NOI18N
        setResizable(false);

        lbCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCod.setText("COD:");

        lbDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDescricao.setText("DESCRIÇÃO:");

        taDescricao.setColumns(20);
        taDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taDescricao.setRows(3);
        jScrollPane1.setViewportView(taDescricao);

        tfCod.setDocument(new TextFieldLimit(6));
        tfCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfCod.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfCod.setText("000000");

        lbPorcao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPorcao.setText("PORÇÃO:");

        tfPorcao.setDocument(new TextFieldLimit(6));
        tfPorcao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPreco.setText("PREÇO:");

        tfPreco.setDocument(new TextFieldLimit(6));
        tfPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPreco.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfPreco.setText("0,00");

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRootLayout = new javax.swing.GroupLayout(pnRoot);
        pnRoot.setLayout(pnRootLayout);
        pnRootLayout.setHorizontalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnRootLayout.createSequentialGroup()
                        .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRootLayout.createSequentialGroup()
                                .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPorcao, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                            .addGroup(pnRootLayout.createSequentialGroup()
                                .addComponent(lbCod)
                                .addGap(75, 75, 75)
                                .addComponent(lbPorcao)))
                        .addGap(18, 18, 18)
                        .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPreco)))
                    .addGroup(pnRootLayout.createSequentialGroup()
                        .addComponent(lbDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnRootLayout.setVerticalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCod)
                    .addComponent(lbPorcao)
                    .addComponent(lbPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPorcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(767, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        ProdutoDAO dao = new ProdutoDAO();
        
        String codigo = tfCod.getText();
        String porcao = tfPorcao.getText();
        String precoStr = tfPreco.getText();
        String descricao = taDescricao.getText();
        
        //verificaCampos();
        if (codigo.isBlank()) {
            JOptionPane.showMessageDialog(
                rootPane,
                "Código inválido! Digite um válido.",
                "Novo Produto",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        if (descricao.isBlank()) {
            JOptionPane.showMessageDialog(
                rootPane,
                "Descrição inválida! Digite uma válida.",
                "Novo Produto",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        if (precoStr.isBlank()) {
            JOptionPane.showMessageDialog(
                rootPane,
                "Preço inválido! Digite um válido.",
                "Novo Produto",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        try {
            // Converte o preço de String para double
            NumberFormat fmt = NumberFormat.getInstance();
            double preco = fmt.parse(precoStr).doubleValue();
            
            // Salva o produto
            Produto produto = new Produto(codigo, descricao, porcao, preco);
            dao.create(rootPane, produto);
            searchable.add(produto);
        } catch (ParseException ex) {
            Logger.getLogger(TAG).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbPorcao;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JPanel pnRoot;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfPorcao;
    private javax.swing.JTextField tfPreco;
    // End of variables declaration//GEN-END:variables
}
